ALTER TABLE questions
  ADD COLUMN IF NOT EXISTS calibration_confidence DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS effective_difficulty DOUBLE PRECISION NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS confusion_index DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS trap_efficiency DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS time_pressure_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS quality_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS auto_quality_flag VARCHAR(40) NOT NULL DEFAULT 'insufficient_data';

CREATE INDEX IF NOT EXISTS ix_questions_quality_flag ON questions(auto_quality_flag);
